#!/usr/bin/env bash

##
# Writes aggregated globals to data/asc/global.vars.sh and .env.
#
# When executed as a script, bootstraps ASC then writes (expects globals already
# aggregated — prefer calling from instance init after f_global_aggregate).
# When sourced, only defines f_global_write().
#
# @see f_instance_init() in asc/instance/instance.inc.sh
#
# @example
#   # After bootstrap + aggregate :
#   . asc/instance/write_globals.sh
#   f_global_write
#

##
# Persists current GLOBALS into git-ignored instance files.
#
f_global_write() {
  local gn_arr=()
  local global_name=''
  local global_val=''
  local has_double_quote=0
  local has_single_quote=0
  local readonly
  local v
  local db_id
  local db_var
  local prefixed_db_var
  local db_vars_list=''
  local -A non_readonly_dict=()
  local vars_sh_buf=''
  local env_buf=''

  if [[ -z "$GLOBALS_COUNT" ]]; then
    echo >&2
    echo "Error in f_global_write() - $BASH_SOURCE line $LINENO: nothing to write." >&2
    echo "Aborting (1)." >&2
    echo >&2
    return 1
  fi

  echo "Writing global (env) vars to data/asc/global.vars.sh ..."

  # Precompute DB-related names that must stay writable (not readonly).
  if [[ -n "$ASC_DB_IDS" ]]; then
    f_db_vars_list
    for v in $db_vars_list; do
      db_var="DB_$v"
      non_readonly_dict["$db_var"]=1
      for db_id in $ASC_DB_IDS; do
        prefixed_db_var="${db_id}_${db_var}"
        f_str_uppercase "$prefixed_db_var" 'prefixed_db_var'
        non_readonly_dict["$prefixed_db_var"]=1
      done
    done
  fi

  vars_sh_buf='#!/usr/bin/env bash

##
# Current instance global (env) vars declarations.
#
# This file is automatically generated during "instance init", and it will be
# entirely overwritten every time it is executed.
#
# @see f_instance_init() in asc/instance/instance.inc.sh
# @see f_global_write() in asc/instance/write_globals.sh
#

'

  for global_name in ${GLOBALS['.sorting']}; do
    f_str_split1 'gn_arr' "$global_name" '|'

    global_name="${gn_arr[1]}"
    global_val="${!global_name}"

    has_double_quote=0
    has_single_quote=0

    case "$global_val" in *'"'*)
      has_double_quote=1
    esac

    case "$global_val" in *"'"*)
      has_single_quote=1
    esac

    # TODO is there a way out of this ? Considered edge case, #YAGNI.
    if [[ $has_double_quote == 1 && $has_single_quote == 1 ]]; then
      echo
      echo "Notice : the global $global_name has the following value :"
      echo "  ${!global_name}"
      echo "  -> it appears to have both single quotes and double quotes, which can cause unexpected issues."
      echo
    fi

    if [[ -n "${non_readonly_dict[$global_name]+x}" ]]; then
      readonly=''
    else
      readonly='readonly '
    fi

    if [[ -z "$global_val" ]]; then
      vars_sh_buf+="${readonly}$global_name=''"$'\n'
    else
      if [[ $has_single_quote != 1 ]]; then
        vars_sh_buf+="${readonly}$global_name='$global_val'"$'\n'
      else
        # TODO do we want to escape any '$' sign when using double quotes ?
        # TODO [evol] see if there's a better workaround for quotes. Right now,
        # we have to trim any ' or " prefix + suffix manually here.
        # @see asc/vendor/bash-yaml/script/yaml.sh
        global_val="${global_val%\'}"
        global_val="${global_val#\'}"
        global_val="${global_val%\"}"
        global_val="${global_val#\"}"
        vars_sh_buf+="${readonly}$global_name=\"$global_val\""$'\n'
      fi
    fi

    # Also write globals to git-ignored '.env' file for Makefile and other tools
    # like docker-compose.
    case "$global_val" in *' '*|*'$'*|*'#'*|*'['*|*']'*|*'*|*'*|*'&'*|*'*'*|*'"'*|*"'"*)
      if [[ $has_single_quote != 1 ]]; then
        global_val="'$global_val'"
      else
        global_val="\"$global_val\""
      fi
    esac

    if [[ -z "$global_val" ]]; then
      env_buf+="$global_name="$'\n'
    else
      env_buf+="$global_name=$global_val"$'\n'
    fi
  done

  printf '%s' "$vars_sh_buf" > data/asc/global.vars.sh
  printf '%s' "$env_buf" > .env

  echo "Writing global (env) vars to data/asc/global.vars.sh : done."
  echo
}

# Entry point (skipped when this file is sourced).
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  . asc/bootstrap.sh
  f_global_write
fi
