#!/usr/bin/env bash

##
# Writes make entrypoints to data/asc/pivots.mk (and test-case registry cache).
#
# When executed as a script, bootstraps ASC then generates.
# When sourced, only defines f_make_generate() and f_make_generate_test_cases().
#
# Warm wrap still uses eager helpers in make.inc.sh (list / unescape / hardcoded).
# @see f_instance_init() in asc/instance/instance.inc.sh
# @see f_make_list_hardcoded() in asc/make/make.inc.sh
#
# @example
#   # After bootstrap :
#   . asc/make/generate.sh
#   f_make_generate
#

##
# Writes make entrypoints to data/asc/pivots.mk
#
# Generates a Makefile include with tasks corresponding to every subject-action
# in current instance.
#
# Also generates a script called before any make entry point to do the same as :
# @see f_make_check_args()
#
f_make_generate() {
  local i
  local make_entry_point
  local real_script

  local pivots_arr=()
  local real_scripts_arr=()

  # All except the hardcoded ones.
  f_make_list_entry_points

  if [[ -z "$real_scripts_arr" ]]; then
    echo "Notice in f_make_generate() - $BASH_SOURCE line $LINENO: no Make entry points have been found."
    return
  fi

  echo "Writing Makefile include data/asc/pivots.mk ..."
  rm -f data/asc/generated.mk

  cat > data/asc/pivots.mk <<'EOF'

##
# Current instance Makefile include.
#
# Contains generic tasks for subject-action entry points (default scripts).
#
# This file is automatically generated during "instance init", and it will be
# entirely overwritten every time it is executed.
#
# @see f_instance_init() in asc/instance/instance.inc.sh
# @see f_make_generate() in asc/make/generate.sh
#

EOF

  for i in "${!pivots_arr[@]}"; do
    make_entry_point="${pivots_arr[i]}"
    real_script="${real_scripts_arr[i]}"

    echo ".PHONY: $make_entry_point
$make_entry_point:
	@ asc/make/call_wrap.make.sh $real_script \$(MAKECMDGOALS)
" >> data/asc/pivots.mk

  done

  f_make_generate_test_cases

  echo "Writing Makefile include data/asc/pivots.mk : done."
  echo

  # We'll also need to generate a "normal" shell script (not bash) to check
  # that among all arguments sent to a Make entry point, none are "reserved"
  # values - i.e. that would trigger unwanted other targets.
  echo "Creating cache file data/asc/cache/pivots.sh ..."
  rm -f data/asc/cache/make.sh

  # Including the hardcoded ones (this is only used for the safety check).
  f_make_list_hardcoded

  local cache_file='data/asc/cache/pivots.sh'
  local make_entries_code_gen=''
  local real_scripts_code_gen=''

  # Replace contents in case cache file exists.
  cat > "$cache_file" <<'SHELL_SCRIPT_HEAD'
#!/usr/bin/env bash

##
# Cache the list of make entry points.
#
# This script is generated during "instance init".
#
# @see f_instance_init() in asc/instance/instance.inc.sh
# @see f_make_generate() in asc/make/generate.sh
#

pivots_arr=()
real_scripts_arr=()

SHELL_SCRIPT_HEAD

  for i in "${!pivots_arr[@]}"; do
    make_entry_point="${pivots_arr[i]}"
    real_script="${real_scripts_arr[i]}"

    make_entries_code_gen+="pivots_arr+=('$make_entry_point')
"
    real_scripts_code_gen+="real_scripts_arr+=('$real_script')
"
  done

  if [[ -f data/asc/cache/test-cases.sh ]]; then
    # shellcheck disable=SC1090
    . data/asc/cache/test-cases.sh
    for make_entry_point in "${test_case_registry_targets_arr[@]}"; do
      make_entries_code_gen+="pivots_arr+=('$make_entry_point')
"
      real_scripts_code_gen+="real_scripts_arr+=('asc/test/single_case.make.sh')
"
    done
  fi

  echo '' >> "$cache_file"
  echo "$make_entries_code_gen" >> "$cache_file"
  echo '' >> "$cache_file"
  echo "$real_scripts_code_gen" >> "$cache_file"

  echo "Creating cache file data/asc/cache/pivots.sh : done."
  echo
}

##
# Append per-case make targets and write test-case registry cache.
#
# Uses pivots_arr and real_scripts_arr arrays from calling scope (f_make_generate).
#
f_make_generate_test_cases() {
  local batch_task=''
  local batch_script=''
  local case_stem=''
  local case_target=''
  local cache_file="${ASC_TEST_CASE_CACHE:-data/asc/cache/test-cases.sh}"

  if [[ "$(type -t f_test_batch_exec)" != function ]]; then
    # shellcheck disable=SC1091
    . asc/test/test.opt-inc.sh
  fi

  local cache_dir
  local i=''

  local -a tc_targets_arr=()
  local -a tc_batch_tasks_arr=()
  local -a tc_stems_arr=()
  local -a tc_modes_arr=()
  local -a tc_batch_dirs_arr=()
  local -a tc_batch_scripts_arr=()

  if [[ -z "$cache_file" ]]; then
    cache_file='data/asc/cache/test-cases.sh'
  fi

  cache_dir="${cache_file%/*}"
  mkdir -p "$cache_dir"

  for i in "${!pivots_arr[@]}"; do
    batch_task="${pivots_arr[i]}"
    batch_script="${real_scripts_arr[i]}"

    test_case_mode=''
    test_case_batch_dir=''
    test_case_stems=''

    f_test_discover_batch_cases "$batch_script" || continue

    for case_stem in $test_case_stems; do
      case_target="$(f_test_case_make_target "$batch_task" "$case_stem")"

      if f_in_array "$case_target" 'tc_targets_arr'; then
        continue
      fi

      tc_targets_arr+=("$case_target")
      tc_batch_tasks_arr+=("$batch_task")
      tc_stems_arr+=("$case_stem")
      tc_modes_arr+=("$test_case_mode")
      tc_batch_dirs_arr+=("$test_case_batch_dir")
      tc_batch_scripts_arr+=("$batch_script")

      echo ".PHONY: $case_target
$case_target:
	@ asc/make/call_wrap.make.sh asc/test/single_case.make.sh \$(MAKECMDGOALS)
" >> data/asc/pivots.mk
    done
  done

  if [[ ${#tc_targets_arr[@]} -eq 0 ]]; then
    rm -f "$cache_file"
    return 0
  fi

  echo "Writing test-case registry ${cache_file} ..."

  cat > "$cache_file" <<'EOF'
#!/usr/bin/env bash

##
# Generated test-case registry for f_test_run_case_by_target().
#
# @see f_make_generate_test_cases() in asc/make/generate.sh
#

test_case_registry_targets_arr=()
test_case_registry_batch_tasks_arr=()
test_case_registry_stems_arr=()
test_case_registry_modes_arr=()
test_case_registry_batch_dirs_arr=()
test_case_registry_batch_scripts_arr=()

EOF

  {
    for i in "${!tc_targets_arr[@]}"; do
      echo "test_case_registry_targets_arr+=('${tc_targets_arr[i]}')"
      echo "test_case_registry_batch_tasks_arr+=('${tc_batch_tasks_arr[i]}')"
      echo "test_case_registry_stems_arr+=('${tc_stems_arr[i]}')"
      echo "test_case_registry_modes_arr+=('${tc_modes_arr[i]}')"
      echo "test_case_registry_batch_dirs_arr+=('${tc_batch_dirs_arr[i]}')"
      echo "test_case_registry_batch_scripts_arr+=('${tc_batch_scripts_arr[i]}')"
      echo ''
    done
  } >> "$cache_file"

  echo "Writing test-case registry ${cache_file} : done."
  echo
}

# Entry point (skipped when this file is sourced).
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  . asc/bootstrap.sh
  f_make_generate
fi
